name       : xaut
version    : 0.5.0
release    : 3
source     :
    - https://ufpr.dl.sourceforge.net/project/xautomation/xautomation/xaut-0.5.0.tar.gz : 53fb04ea94ea2d0a3c885fde92a0576085cc1ee751dbbd4490253fcc869d7916
license    : Python-2.0
component  : programming.python
summary    : Python library to automate X11
description: |
    Python library to automate X11
builddeps  :
    - pkgconfig(python3)
    - pkgconfig(xtst)
    - swig
setup      : |
    %patch -p1 < $pkgfiles/0001-Fix-Exception-raise.patch
    %patch -p1 < $pkgfiles/0001-Makefile.in-use-our-CFLAGS.patch

    %configure
build      : |
    %make
install    : |
    cd python
    python3 setup.py install --root=$installdir
