name       : xaut
version    : 0.4.5
release    : 2
source     :
    - http://ufpr.dl.sourceforge.net/project/xautomation/xautomation/xaut-0.4.5.tar.gz : b6c70e531f509f9a5f1e4a56466e0a2480153952b3b2ae824a505a303bdefd54
license    : Python-2.0
component  : programming.python
summary    : Python library to automate X11
description: |
    Python library to automate X11
builddeps  :
    - pkgconfig(python3)
    - pkgconfig(xtst)
    - swig
setup      : |
    %patch -p1 < $pkgfiles/0001-Fix-Exception-raise.patch
    %configure
build      : |
    %make
install    : |
    cd python
    python2 setup.py install --root=$installdir
    python3 setup.py install --root=$installdir
